### ISSUE TITLE
Can not run jobs in series

### ISSUE THREAD

**Issue by jens120** [svenholcombe/matlab-lsdyna#6]
I would like to run jobs in series with the following script:

```matlab
baseFolder = 'C:\Temp\FolderToSims';
for i = 1:6
    simFolder = fullfile(baseFolder,sprintf('sim%d',i));
    S(i) = lsdyna.simulation(fullfile(simFolder,'plates.mat100.k'));
end
S.run % Each simulation will be run, one after the other
```

LS-Dyna does not start and I get the error message:
```
Error using isempty
Too many input arguments.

Error in lsdyna.simulation/run (line 127)
            if ~isempty(this.PreSimCallback)

Error in series (line 11)
S.run % Each simulation will be run, one after the other
```
I included the above script and test .k file in a repository: https://github.com/jens120/Run_LS-DynaWithMATLAB

**Comment by SamBasin** [comment]
you didnt happen to get this working did you?

**Comment by jens120** [comment]
No, I didn't...

**Comment by sigbjor** [comment]
I believe that your input argument becomes a 1x1 cell when you loop, and thus it is not a valid input to lsdyna.simulation(), which accepts character arrays. You can try to first store the 1x1 cell, and then extract the character array by using braces, as such:

baseFolder = 'C:\Temp\FolderToSims';
for i = 1:6
    simFolder = fullfile(baseFolder,sprintf('sim%d',i));
    simFile = fullfile(simFolder,'plates.mat100.k'):
    S(i) = lsdyna.simulation(simFile{1});
end
S.run % Each simulation will be run, one after the other

**Comment by jens120** [comment]
@sigbjor Thank you for your response. I will close the issue. No longer using LS-Dyna so I can’t test.
